version: "3.7"

services:
  caddy:
    container_name: caddy
    build:
      context: .
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    restart: unless-stopped

volumes:
  caddy-data:
    external: true
  caddy-config:
